name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Run Stryker.js mutation testing
        run: npx stryker run

      - name: Mutation Report Action
        uses: johanholmerin/mutation-report-action@0.2.0

      - name: Mutation Annotation Report
        uses: johanholmerin/mutation-report-action@0.2.0
        if: ${{ always() }} # Upload even if tests don't pass testing threshold
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: './reports/mutation/mutation.json' # Optional, default
