name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
      
      - name: Install Stryker.js Mocha plugin
        run: npm install @stryker-mutator/mocha-runner --save-dev

      - name: Install Stryker.js Mocha plugin
        run: npm install @stryker-mutator/mocha-runner --save-dev

      - name: Install mocha-runner plugin
        run: npm install @stryker-mutator/mocha-runner --save-dev
      
      - name: Run Stryker.js mutation testing
        run: npx stryker run --plugins mocha-runner

